export const chats = [
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)0",
    username: "Jett.Green",
    avatar_url: "https://picsum.photos/60?random=1",
    message:
      "copying the matrix won't do anything, we need to generate the auxiliary XSS panel!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)1",
    username: "Gavin69",
    avatar_url: "https://picsum.photos/60?random=2",
    message:
      "If we bypass the microchip, we can get to the IB card through the haptic HTTP firewall!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)2",
    username: "Gavin69",
    avatar_url: "https://picsum.photos/60?random=2",
    message:
      "transmitting the protocol won't do anything, we need to reboot the back-end RSS application!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)3",
    username: "Jarrett83",
    avatar_url: "https://picsum.photos/60?random=4",
    message: "I'll hack the 1080p JBOD sensor, that should port the AI feed!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)4",
    username: "Shyanne_Hahn42",
    avatar_url: "https://picsum.photos/60?random=5",
    message:
      "Try to calculate the JBOD interface, maybe it will hack the multi-byte microchip!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)5",
    username: "Alycia_Herman",
    avatar_url: "https://picsum.photos/60?random=6",
    message:
      "If we override the pixel, we can get to the SDD panel through the haptic THX monitor!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)6",
    username: "Roslyn45",
    avatar_url: "https://picsum.photos/60?random=7",
    message:
      "Try to calculate the JSON protocol, maybe it will synthesize the haptic pixel!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)7",
    username: "Roslyn45",
    avatar_url: "https://picsum.photos/60?random=7",
    message:
      "You can't compress the monitor without backing up the cross-platform SCSI monitor!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)8",
    username: "Shyanne.Kihn78",
    avatar_url: "https://picsum.photos/60?random=9",
    message:
      "The SCSI protocol is down, reboot the auxiliary microchip so we can calculate the IB interface!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)9",
    username: "Shyanne.Kihn78",
    avatar_url: "https://picsum.photos/60?random=9",
    message:
      "generating the firewall won't do anything, we need to calculate the bluetooth COM microchip!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)10",
    username: "Shyanne.Kihn78",
    avatar_url: "https://picsum.photos/60?random=9",
    message:
      "If we calculate the card, we can get to the IB protocol through the auxiliary AGP interface!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)11",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message:
      "If we hack the bus, we can get to the ADP bus through the auxiliary PCI application!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)12",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message:
      "I'll quantify the multi-byte SQL bus, that should pixel the RSS bus!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)13",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message:
      "bypassing the monitor won't do anything, we need to input the primary SQL matrix!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)14",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message:
      "copying the port won't do anything, we need to connect the primary AGP program!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)15",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message:
      "generating the alarm won't do anything, we need to navigate the bluetooth HDD matrix!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)16",
    username: "Damaris_Cartwright72",
    avatar_url: "https://picsum.photos/60?random=12",
    message: "We need to compress the digital PCI hard drive!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)17",
    username: "Vito28",
    avatar_url: "https://picsum.photos/60?random=18",
    message:
      "If we connect the pixel, we can get to the THX matrix through the virtual SSL hard drive!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)18",
    username: "Vito28",
    avatar_url: "https://picsum.photos/60?random=18",
    message: "We need to program the mobile GB array!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)19",
    username: "Brooks.Flatley",
    avatar_url: "https://picsum.photos/60?random=20",
    message:
      "Use the multi-byte USB bus, then you can compress the optical matrix!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)20",
    username: "Brooks.Flatley",
    avatar_url: "https://picsum.photos/60?random=20",
    message:
      "Try to reboot the EXE microchip, maybe it will input the virtual pixel!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)21",
    username: "Brooks.Flatley",
    avatar_url: "https://picsum.photos/60?random=20",
    message:
      "If we compress the protocol, we can get to the IB firewall through the 1080p AI alarm!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)22",
    username: "Payton.Funk41",
    avatar_url: "https://picsum.photos/60?random=23",
    message: "You can't copy the array without copying the primary RSS array!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)23",
    username: "Payton.Funk41",
    avatar_url: "https://picsum.photos/60?random=23",
    message:
      "The SSL circuit is down, synthesize the auxiliary firewall so we can synthesize the JSON circuit!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)24",
    username: "Freeman_Thiel",
    avatar_url: "https://picsum.photos/60?random=25",
    message: "We need to transmit the solid state THX transmitter!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)25",
    username: "Freeman_Thiel",
    avatar_url: "https://picsum.photos/60?random=25",
    message:
      "The CSS alarm is down, reboot the redundant feed so we can bypass the FTP protocol!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)26",
    username: "Veda.Yundt",
    avatar_url: "https://picsum.photos/60?random=27",
    message:
      "If we calculate the port, we can get to the COM microchip through the virtual SCSI driver!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)27",
    username: "Pearl_Schamberger",
    avatar_url: "https://picsum.photos/60?random=28",
    message:
      "I'll transmit the haptic SAS port, that should bandwidth the ADP program!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)28",
    username: "Milan47",
    avatar_url: "https://picsum.photos/60?random=29",
    message:
      "You can't calculate the array without programming the solid state RSS hard drive!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)29",
    username: "Wyatt91",
    avatar_url: "https://picsum.photos/60?random=30",
    message:
      "Use the digital SQL transmitter, then you can hack the solid state driver!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)30",
    username: "Wyatt91",
    avatar_url: "https://picsum.photos/60?random=30",
    message:
      "You can't input the bandwidth without backing up the neural JBOD panel!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)31",
    username: "Rodrick4",
    avatar_url: "https://picsum.photos/60?random=32",
    message:
      "I'll back up the online SMTP application, that should card the SSL pixel!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)32",
    username: "Rodrick4",
    avatar_url: "https://picsum.photos/60?random=32",
    message:
      "The AGP alarm is down, compress the auxiliary hard drive so we can bypass the PNG circuit!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)33",
    username: "Rodrick4",
    avatar_url: "https://picsum.photos/60?random=32",
    message:
      "generating the protocol won't do anything, we need to navigate the digital AGP application!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)34",
    username: "Rodrick4",
    avatar_url: "https://picsum.photos/60?random=32",
    message:
      "The XSS protocol is down, connect the primary matrix so we can quantify the JSON alarm!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)35",
    username: "Rodrick4",
    avatar_url: "https://picsum.photos/60?random=32",
    message:
      "If we override the capacitor, we can get to the HTTP system through the virtual EXE protocol!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)36",
    username: "Arturo10",
    avatar_url: "https://picsum.photos/60?random=37",
    message:
      "overriding the program won't do anything, we need to transmit the primary SCSI pixel!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)37",
    username: "Arturo10",
    avatar_url: "https://picsum.photos/60?random=37",
    message:
      "You can't program the driver without synthesizing the solid state SMTP panel!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)38",
    username: "Erling_Dicki86",
    avatar_url: "https://picsum.photos/60?random=39",
    message:
      "If we input the matrix, we can get to the AI card through the multi-byte HTTP card!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)39",
    username: "Erling_Dicki86",
    avatar_url: "https://picsum.photos/60?random=39",
    message:
      "quantifying the matrix won't do anything, we need to index the digital SAS transmitter!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)40",
    username: "Erling_Dicki86",
    avatar_url: "https://picsum.photos/60?random=39",
    message: "We need to parse the online USB feed!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)41",
    username: "Alice81",
    avatar_url: "https://picsum.photos/60?random=42",
    message:
      "Use the mobile FTP hard drive, then you can override the 1080p hard drive!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)42",
    username: "Vanessa_Thompson28",
    avatar_url: "https://picsum.photos/60?random=43",
    message:
      "You can't compress the hard drive without quantifying the optical CSS monitor!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)43",
    username: "Vanessa_Thompson28",
    avatar_url: "https://picsum.photos/60?random=43",
    message:
      "You can't reboot the alarm without copying the online CSS matrix!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)44",
    username: "Macie30",
    avatar_url: "https://picsum.photos/60?random=45",
    message:
      "Try to calculate the XSS firewall, maybe it will synthesize the auxiliary application!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)45",
    username: "Blair_Brekke38",
    avatar_url: "https://picsum.photos/60?random=46",
    message: "We need to generate the solid state PCI microchip!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)46",
    username: "Blair_Brekke38",
    avatar_url: "https://picsum.photos/60?random=46",
    message: "Use the neural SSL feed, then you can hack the wireless port!",
    type: "text",
    edited: false,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)47",
    username: "Wendy17",
    avatar_url: "https://picsum.photos/60?random=48",
    message: "We need to copy the back-end XSS interface!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)48",
    username: "Sherwood12",
    avatar_url: "https://picsum.photos/60?random=49",
    message:
      "You can't program the alarm without indexing the solid state XSS card!",
    type: "text",
    edited: true,
    attachments: [],
  },
  {
    id: "Sat Feb 27 2021 12:01:44 GMT+0530 (India Standard Time)49",
    username: "Sherwood12",
    avatar_url: "https://picsum.photos/60?random=49",
    message:
      "Try to index the ADP protocol, maybe it will index the bluetooth sensor!",
    type: "text",
    edited: true,
    attachments: [],
  },
];
